spring:
  application:
    name: pocari

  datasource:
    url: jdbc:mariadb://cloudyong.store:10010/fourstit
    username: mabem
    password: beyond5%
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true


logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate: DEBUG
